In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from evolvepro.src.evolve import evolve
from sklearn.ensemble import RandomForestRegressor

In [3]:
evolve(embeddings_files=[f"embeddings_esm2_650m.csv"],  # can have multiple embeddings files
       round_files=["activity.xlsx"],    # can have multiple activity files
       output_file="example_predictions.csv")

Loaded experimental data with shape: (4, 1) -> (variants, activity_dimensions)
Quick peek:
         activity
variant
M1F           1.5
S3H           0.0
T4K           4.0
WT            1.0
Loaded embeddings with shape: (172, 1280) -> (variants, embeddings_width)
Quick peek:
            dim_0     dim_1     dim_2     dim_3     dim_4
variant
A2C      0.108424  0.085872  0.179303  0.120952 -0.156383
A2D      0.101514  0.104516  0.135416  0.143987 -0.088275
A2E      0.104881  0.102321  0.141485  0.111109 -0.096601
A2F      0.110265  0.093011  0.153894  0.140174 -0.134468
A2G      0.073179  0.077786  0.111352  0.140143 -0.120142
Fitting regression model to activity with 1 dimensions.
Wrote predictions to example_predictions.csv

     rank  activity_actual  activity_pred
T4K     1              4.0         2.9100
A2K     2              NaN         2.1125
F7K     3              NaN         2.1125
V5K     4              NaN         2.0425
T4C     5              NaN         1.9675
..    ...              ...            ...
S3N   168              NaN         1.3800
S3D   169              NaN         1.3575
K6T   170              NaN         1.3375
S3P   171              NaN         1.3300
S3H   172              0.0         0.7325

[172 rows x 3 columns]

In [5]:
evolve(embeddings_files=[f"embeddings_esm2_650m.csv"],  # can have multiple embeddings files
       round_files=["activity.xlsx"],    # can have multiple activity files
       output_file="example_predictions.csv",
       regression_model="gradientboosting")      # can pick from a selection of regression models

Loaded experimental data with shape: (4, 1) -> (variants, activity_dimensions)
Quick peek:
         activity
variant
M1F           1.5
S3H           0.0
T4K           4.0
WT            1.0
Loaded embeddings with shape: (172, 1280) -> (variants, embeddings_width)
Quick peek:
            dim_0     dim_1     dim_2     dim_3     dim_4
variant
A2C      0.108424  0.085872  0.179303  0.120952 -0.156383
A2D      0.101514  0.104516  0.135416  0.143987 -0.088275
A2E      0.104881  0.102321  0.141485  0.111109 -0.096601
A2F      0.110265  0.093011  0.153894  0.140174 -0.134468
A2G      0.073179  0.077786  0.111352  0.140143 -0.120142
Fitting regression model to activity with 1 dimensions.
Wrote predictions to example_predictions.csv

     rank  activity_actual  activity_pred
T4K     1              4.0       2.972979
S3K     2              NaN       2.603136
A2K     3              NaN       2.419633
Y8Q     4              NaN       2.413719
F7K     5              NaN       2.401983
..    ...              ...            ...
T4R   168              NaN       1.086695
A2P   169              NaN       1.075617
Y8P   170              NaN       1.009549
W9K   171              NaN       1.001751
S3H   172              0.0       0.874703

[172 rows x 3 columns]

In [4]:
evolve(embeddings_files=[f"embeddings_esm2_650m.csv"],  # can have multiple embeddings files
       round_files=["activity.xlsx"],    # can have multiple activity files
       output_file="example_predictions.csv",
       regression_model=RandomForestRegressor(   # can also pass in a custom regression model
           n_estimators=100,
           criterion='friedman_mse',
           random_state=1)
       )

Loaded experimental data with shape: (4, 1) -> (variants, activity_dimensions)
Quick peek:
         activity
variant
M1F           1.5
S3H           0.0
T4K           4.0
WT            1.0
Loaded embeddings with shape: (172, 1280) -> (variants, embeddings_width)
Quick peek:
            dim_0     dim_1     dim_2     dim_3     dim_4
variant
A2C      0.108424  0.085872  0.179303  0.120952 -0.156383
A2D      0.101514  0.104516  0.135416  0.143987 -0.088275
A2E      0.104881  0.102321  0.141485  0.111109 -0.096601
A2F      0.110265  0.093011  0.153894  0.140174 -0.134468
A2G      0.073179  0.077786  0.111352  0.140143 -0.120142
Fitting regression model to activity with 1 dimensions.
Wrote predictions to example_predictions.csv

     rank  activity_actual  activity_pred
T4K     1              4.0          2.930
A2K     2              NaN          2.275
F7K     3              NaN          2.135
S3K     4              NaN          2.065
V5K     5              NaN          2.050
..    ...              ...            ...
K6T   168              NaN          1.340
M1D   169              NaN          1.320
M1E   170              NaN          1.290
W9P   171              NaN          1.280
S3H   172              0.0          0.810

[172 rows x 3 columns]